copyright: "Copyright \xA9 None - 2021 Astemes"
docs_dir: docs
extra:
  generator: true
extra_css:
- Style/style.css
markdown_extensions:
  - plantuml_markdown:
      server: "http://www.plantuml.com/plantuml"
nav:
- Design Description: Design Description/System Design Description.md
- Manuals:
  - Developer: Manuals/Developer/Developers Manual.md
  - Installation: Manuals/Installation/Installation Manual.md
  - Service: Manuals/Service/Service Manual.md
  - User: Manuals/User/User Manual.md
- UML Test: UML Test/uml test.md
- Version History: Version History/Version History.md
plugins:
- search
- with-pdf
repo_url: https://github.com/astemes
site_author: Anton Sundqvist
site_name: Template Project
site_url: http://astemes.com
theme:
  favicon: Style/logo.png
  logo: Style/logo.png
  name: material
